### ISSUE TITLE
Dummy driver: multi-step method results

### ISSUE THREAD

**Issue by lorisercole** [dgbowl/tomato#34]
With the `dummy` driver, the results returned from a multi-step method are not split into steps but are concatenated into a single step.

Example payload:
```
version: "0.1"
sample:
    name: fake_sample
    capacity: 1.0
method:
  - device: "worker"
    technique: "random"
    time: 35
    delay: 2
  - device: "worker"
    technique: "random"
    time: 20
    delay: 1
```
The output json file contains 38 points assigned to a single step, instead of 18+20.

**Comment by lorisercole** [comment]
Oh, I see. I agree that in this case it does not make sense to separate the cycle into 3 steps, and I also wonder if a series of cycles should be separated or concatenated (I guess the last one).

### Loop
Maybe we could modify the `method` schema to look like a for-loop, when dealing with loops, e.g.:
```
version: "0.1"
sample:
    name: fake_sample
    capacity: 1.0
method:
  - device: "MPG2"
    technique: "loop"
    n_loops: 10
    submethod:
    - device: "MPG2"
      technique: "constant_current"
      current: "C/10"
      ...
    - device: "MPG2"
      technique: "constant_voltage"
      voltage: ...
      ...
    - device: "MPG2"
      technique: "constant_current"
      current: "D/10"
      ...
```
That should be translated by `tomato` into the device's instructions (`[CC, CV, CC, LOOP]`).
`yadg` should know it has to concatenate the data of these 3 steps (the `submethod`), and (maybe) that of all the cycles.

### Group
If one does not want a loop, but just wants to concatenate several steps together, we could define a `group`, e.g.:
```
version: "0.1"
sample:
    name: fake_sample
    capacity: 1.0
method:
  - device: "MPG2"
    technique: "group"
    submethod:
    - device: "MPG2"
      technique: "open_circuit_voltage"
      time: "100"
      ...
    - device: "MPG2"
      technique: "constant_current"
      current: "C/10"
      ...
  - device: "MPG2"
    technique: "group"
    submethod:
    - device: "MPG2"
      technique: "open_circuit_voltage"
      time: "100"
      ...
    - device: "MPG2"
      technique: "constant_current"
      current: "D/10"
      ...
```
For `tomato`/`yadg` this works exactly the same. They will translate this into the device's instructions (a single sequence `[OCV, CC, OCV, CC]`); but the output will be split into 2 steps, i.e. the 2 groups defined above.
